# NOMAD 배우 1~20 통합 (10명 기준선과 비교용)
train:
  - C:/Users/timjj/Desktop/캡스톤/drone_dev/data/dataset_nomad/images/train
  - C:/Users/timjj/Desktop/캡스톤/drone_dev/data/dataset_nomad_a11_20/images/train
val:
  - C:/Users/timjj/Desktop/캡스톤/drone_dev/data/dataset_nomad/images/val
  - C:/Users/timjj/Desktop/캡스톤/drone_dev/data/dataset_nomad_a11_20/images/val
nc: 1
names: ['person']
